version: '3'
services:

  daav-fe-angular:
    build: ./client
    container_name: daav-fe
    ports:
      - 80:80   
    environment:
      - APP_ENV=${APP_ENV}

  daav-be-flask:
    build: ./server
    container_name: daav-be
    ports:
      - 5000:5000
    environment:
      - APP_ENV=${APP_ENV}
