// `.env.ts.ts` is generated by the `npm run env` command
import {env} from './.env';

const LABEL = '-prod';
export const FRONTEND_URL = 'http://localhost:80';
export const BACKEND_URL = 'http://localhost:5000';

export const environment = {
  label: 'production',
  dev: false,
  production: true,
  hmr: false,
  useHash: false,
  version: env.npm_package_version + LABEL,
  frontendUrl: FRONTEND_URL,
  backendUrl: BACKEND_URL,
  defaultLanguage: 'itIT',
  supportedLanguages: ['itIT', 'enUS'],
  realTime: true
};
